version: '3'
services:
  app:
    build:
      context: . #path to docker file
      dockerfile: docker/.dockerfileApp
    command: sh -c "npm install && npm run serve" # serve for develop environment only
    volumes:
      - ./frontend/vuejs:/app
      - /app/node_modules/
    environment:
      HOST: 0.0.0.0
  api:
    build:
      context: ./docker/ #path to docker file
      dockerfile: .dockerfileApi
    env_file:
      - .env
    volumes:
      - ./:/usr/share/nginx/api:cached
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
      - redis
  nuxt:
    build:
      context: . #path to docker file
      dockerfile: docker/.dockerfileFrontend
    volumes:
      - ./frontend/nuxtjs:/app
      - /frontend/nuxtjs/node_modules/
    restart: always
    ports:
      - "2223:3000"
    env_file: .env
    command: sh -c "npm install && npm run dev" # serve for develop environment only
    environment:
      HOST: 0.0.0.0
  http-nginx:
    image: nginx:1.14.2-alpine
    ports:
      - "2222:80"
      - "443:443"
    volumes:
      - ./docker/http-nginx-dev.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/usr/share/nginx/api:cached
    links:
      - app
      - api
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    ports:
      - "3333:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./docker/mysql-data:/etc/mysql/conf.d
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
